### PR TITLE
Istanbul (Node) Coverage Reporting

### PR DESCRIPTION
**Pull request by jtwalraven**
This adds capabilities for reporting coverage for the Node reporting tool Istanbul. 
http://gotwarlost.github.io/istanbul/

### CODE REVIEW

**Comment by JTWalraven** [comment]
@ksoichiro

**Comment by jtwalraven** [comment]
@ksoichiro Could you please give feedback on this PR?

**Comment by ksoichiro** [comment]
Sorry for my late reply.
It looks great.

How do I confirm your reporter in your sample?

I tried `./gradlew npmInstall npm_test` and it generated karma report, but I think it doesn't use console reporters.

**Comment by jtwalraven** [comment]
Hey, thanks for your response! 

If I remember correctly, that is how I executed it. I forked the project and further developed it for our needs. I do recall fixing something to get the report on that (though I remember it working for this PR). I won't have time today to get to it, but I will try to get back to you ASAP.

Here is the fork of your project: https://gitlab.com/bti360/gradle-console-reporter

**Comment by jtwalraven** [comment]
I closed this since the changes that worked were not made in the master branch. I will make a new PR with the proper changes.

**Comment by jtwalraven** [comment]
Sorry for the confusion. I created a new PR: #4

**Pull request closed without merging**
